COMPILER_ARGS=-Wall
LIBCURL_COMPILER_ARGS=$(shell curl-config --libs --cflags)
SRC_FOLDER=src
MANIFEST_SOURCE=$(SRC_FOLDER)/manifest.c
OUTPUT_NAME=firefoxext
OUTPUT_FOLDER=bin

build:
	mkdir -p $(OUTPUT_FOLDER)
	gcc $(COMPILER_ARGS) $(LIBCURL_COMPILER_ARGS) $(MANIFEST_SOURCE) -o $(OUTPUT_FOLDER)/$(OUTPUT_NAME)